# Navbar
menus:
  home: /
  archives: /archives/
  # categories: /categories/
  # tags: /tags/
  about: /about/

# Comments
comments:
  post: true
  about: true
# Disqus
# disqus_shortname: uxwind

# Social links
socials:
  github: https://github.com/chnhyg
  twitter: https://twitter.com/chnhyg
  linkedin: https://www.linkedin.com/in/chnhyg

# Miscellaneous
# google_analytics:
